//
//  Privacy.swift
//  Aspen
//
//  Created by Tyler Reckart on 8/28/22.
//

import SwiftUI

struct Privacy: View {
    var body: some View {
        NavigationView {
            ScrollView {
                VStack(alignment: .leading) {
                    Text("Overview")
                        .font(.title3)
                        .fontWeight(.bold)
                        .padding([.top, .bottom])
                    
                    Text("This Privacy Policy decribes how your personal information is handled in Aspen.")
                    
                    Text("We Collect No Personal Information")
                        .font(.title3)
                        .fontWeight(.bold)
                        .padding([.top, .bottom])
                    
                    Text("We do not collect, use, save, or have access to any of your personal data stored in Aspen.")
                        .padding(.bottom)
                    Text("Individual settings and any data generated by Aspen are not personal and are stored only on your device. You may be asked to provide access to your photo library, but this is only so that you may open your photos in Aspen and save them in your stored notes. We do not process that information at all and have no access to it.")
                        .padding(.bottom)
                    Text("In addition, if you take a photo using Aspen, location data is saved in the image, but we have no access to that data and it is not shared with anyone unless you yourself choose to share the image.")
                    
                    Text("Contact Us")
                        .font(.title3)
                        .fontWeight(.bold)
                        .padding([.top, .bottom])
                    
                    Text("If you have any questions about this Privacy Policy, feel free to contact us at [info@haptic.software](mailto:info@haptic.software).")
                    
                    Spacer()
                }
                .padding()
            }
        }
        .navigationTitle("Privacy Policy")
        .navigationBarTitleDisplayMode(.inline)
    }
}
